/**
 * This file was generated by the Jeddict
 */
package Entity.domain;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.ForeignKey;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;

@NamedQueries({
    @NamedQuery(name = "getAllCourses", query = ("Select c FROM Course c"))
    ,
@NamedQuery(name = "getCourseByName", query = ("Select c FROM Course c where c.name LIKE :name"))})

@Entity
public class Course {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "course_id")
    private Long courseId;

    @Basic
    private String name;

    @Column(nullable = false)
    @Basic
    private int points;

    @ManyToOne
    @JoinColumn(nullable = true)
    private Teacher teacher;

    @ManyToMany(mappedBy = "courses")
    private Set<Education> educations;

    public Course() {
    }

    public Course(String name, int points) {
        this.name = name;
        this.points = points;

    }

    public Long getCourseId() {
        return this.courseId;
    }

    public void setCourseId(Long courseId) {
        this.courseId = courseId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getPoints() {
        return this.points;
    }

    public void setPoints(int points) {
        this.points = points;
    }

    public Teacher getTeacher() {
        return this.teacher;
    }

    public void setTeacher(Teacher teacher) {
        this.teacher = teacher;
    }

    public Set<Education> getEducations() {
        if (educations == null) {
            educations = new HashSet<>();
        }
        return this.educations;
    }

    public void setEducations(Set<Education> educations) {
        this.educations = educations;
    }

    public void addEducation(Education education) {
        getEducations().add(education);
    }

    public void removeEducation(Education education) {
        getEducations().remove(education);
    }

    @Override
    public String toString() {
        return "Course{" + "courseId=" + courseId + ", name=" + name + ", points=" + points;
    }

}
