/**
 * This file was generated by the Jeddict
 */
package Entity.domain;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;

@NamedQueries({
    @NamedQuery(name = "getAllStudents", query = ("SELECT s FROM Student s"))
    ,@NamedQuery(name = "getStudentByName", query = ("Select s FROM Student s where s.firstName LIKE :firstName"))
})
@Entity
public class Student extends Person implements Serializable {

    @Basic
    private int points;

    @ManyToOne(fetch = FetchType.EAGER)
    private Education education;

    public Student() {
    }

    public Student(Long personId, String firstName, String lastName, Gender gender) {
        super(personId, firstName, lastName, gender);
        points = 0;

    }

    public int getPoints() {
        return this.points;
    }

    public void setPoints(int points) {
        this.points = points;
    }

    public Education getEducation() {
        return this.education;
    }

    public void setEducation(Education education) {
        this.education = education;
    }

    @Override
    public String toString() {
        return "Student" + super.toString() + "points=" + points + ", education=" + education;
    }

}
