/**
 * This file was generated by the Jeddict
 */
package Entity.domain;

import java.time.LocalDate;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;


//@NamedQueries({
////    Behövs ej då vi sätter värdena direkt i klassen. 
//    @NamedQuery(name = "findStudent", query = "select Student s  WHERE s.personId = :personId"),
//    @NamedQuery (name = "getStudentByName", query = ("Select s FROM Student s where s.firstName =:firstName")),
//    //@NamedQuery (name = "removeStudent", query = ("")
//}) 
@Entity
public class Student extends Person {

    @Basic
    private int points;

    @ManyToOne
    private Education education;

    public Student() {
    }
    
    
    public Student(Long personId, String firstName, String lastName, Gender gender, int points) {
        super(personId, firstName, lastName, gender);
        this.points = points;
        
    }

   

    public int getPoints() {
        return this.points;
    }

    public void setPoints(int points) {
        this.points = points;
    }

    public Education getEducation() {
        return this.education;
    }

    public void setEducation(Education education) {
        this.education = education;
    }

}