/**
 * This file was generated by the Jeddict
 */
package Entity.domain;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;

import javax.persistence.OneToMany;

@NamedQueries({
    @NamedQuery(name = "getAllTeachers", query = ("select t FROM Teacher t "))
    ,@NamedQuery(name = "getTeacherByName", query = ("Select t FROM Teacher t where t.firstName LIKE :firstName"))
})
@Entity
public class Teacher extends Person {

    @Basic
    private int salary;

    @OneToMany(mappedBy = "teacher", cascade = CascadeType.PERSIST, fetch = FetchType.EAGER)
    private Set<Course> courses;

    public Teacher() {
    }

    public Teacher(Long personId, String firstName, String lastName, Gender gender, int Salary) {
        super(personId, firstName, lastName, gender);
        this.salary = Salary;

    }

    public int getSalary() {
        return this.salary;
    }

    public void setSalary(int salary) {
        this.salary = salary;
    }

    public Set<Course> getCourses() {
        if (courses == null) {
            courses = new HashSet<>();
        }
        return this.courses;
    }

    public void setCourses(Set<Course> courses) {
        this.courses = courses;
    }

    public void addCourse(Course course) {
        getCourses().add(course);
        course.setTeacher(this);
    }

    public void removeCourse(Course course) {
        getCourses().remove(course);
        course.setTeacher(null);
    }

    @Override
    public String toString() {
        return "Teacher " + super.toString() + " salary=" + salary + ", courses=" + courses;
    }

}
