/**
 * This file was generated by the Jeddict
 */
package Entity.domain;


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;

import javax.persistence.OneToMany;

/**
 * @author puyaa
 */
@Entity
public class Teacher extends Person {

    @Basic
    private int Salary;

    @OneToMany(mappedBy = "teacher", cascade = CascadeType.PERSIST, fetch = FetchType.LAZY)
    private Set<Course> courses;

    public Teacher() {
    }
    
    public Teacher(Long personId, String firstName, String lastName, Gender gender, int Salary) {
        super(personId, firstName, lastName, gender);
        this.Salary = Salary;
 
    }
    
    

    public int getSalary() {
        return this.Salary;
    }

    public void setSalary(int Salary) {
        this.Salary = Salary;
    }

    public Set<Course> getCourses() {
        if (courses == null) {
            courses = new HashSet<>();
        }
        return this.courses;
    }

    public void setCourses(Set<Course> courses) {
        this.courses = courses;
    }

    public void addCourse(Course course) {
        getCourses().add(course);
        course.setTeacher(this);
    }

    public void removeCourse(Course course) {
        getCourses().remove(course);
        course.setTeacher(null);
    }

}